### ISSUE TITLE
[Suggestion] Rename 'master' to 'main'

### ISSUE THREAD

**Issue by szymski** [dawiddydlinski/janpa-js#1]
Some of you might have noticed, that due to recent events in US, most software developers decided to get rid of names like blacklist/whitelist or master/slave from their projects. I think we should do the same for JanpaJS. Master branch naming is just racist and should not take place in our repo. Please change it to 'main'.

**Comment by dawiddydlinski** [comment]
I think is a good idea. We should respect people of all nationalities in the world. Thanks 👍
